# Generated by Django 2.0.4 on 2020-05-28 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_transactions', to='accounts.Client'),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_payments_methods', to='accounts.Client'),
        ),
    ]
