# Generated by Django 2.0.4 on 2020-05-28 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Checking', 'Checking'), ('Saving', 'Saving'), ('Retirement', 'Retirement')], max_length=255)),
                ('account_number', models.IntegerField()),
                ('funds', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Funds ($)')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('zip', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(null=True)),
                ('account_number', models.IntegerField()),
                ('bank_name', models.CharField(max_length=255)),
                ('swift_code', models.CharField(max_length=255)),
                ('ABA_number', models.IntegerField(default=0)),
                ('SSN', models.IntegerField(default=0)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Client')),
                ('type', models.CharField(choices=[('Company', 'Company'), ('Trust', 'Trust'), ('Institutional account', 'Institutional account'), ('Other entity', 'Other entity')], max_length=255)),
            ],
            bases=('accounts.client',),
        ),
        migrations.CreateModel(
            name='Private',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Client')),
            ],
            bases=('accounts.client',),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_account', to='accounts.Private'),
        ),
    ]
