# Generated by Django 2.0.4 on 2020-05-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_client_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
