# Generated by Django 2.0.4 on 2020-06-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200529_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
