# Generated by Django 2.0.4 on 2020-04-21 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Checking', 'Checking'), ('Saving', 'Saving'), ('Retirement', 'Retirement')], max_length=255)),
                ('account_number', models.IntegerField()),
                ('funds', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Funds ($)')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('zip', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('account_number', models.IntegerField()),
                ('bank_name', models.CharField(max_length=255)),
                ('swift_code', models.CharField(max_length=255)),
                ('ABA_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('minimum_investment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum investment ($)')),
                ('gross_returns', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gross returns (%)')),
                ('net_returns', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net returns (%)')),
                ('description', models.TextField()),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Invested amount ($)')),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Market value ($)')),
                ('bank_name', models.CharField(max_length=255)),
                ('subsidiary_name', models.CharField(max_length=255)),
                ('ABA_number', models.IntegerField()),
                ('company_address', models.CharField(max_length=255)),
                ('account_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PromotionalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/None')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_documents', to='base.Investment')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='investments/None')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_images', to='base.Investment')),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('content', models.FileField(upload_to='remarks_files')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Client')),
                ('type', models.CharField(choices=[('Company', 'Company'), ('Trust', 'Trust'), ('Institutional account', 'Institutional account')], max_length=255)),
            ],
            bases=('base.client',),
        ),
        migrations.CreateModel(
            name='Private',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Client')),
                ('SSN', models.IntegerField(default=0)),
            ],
            bases=('base.client',),
        ),
        migrations.AddField(
            model_name='remark',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_remarks', to='base.Client'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_account', to='base.Private'),
        ),
    ]
