# Generated by Django 2.0.4 on 2020-05-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_photo',
            field=models.ImageField(null=True, upload_to='client_profile'),
        ),
    ]
