# Generated by Django 2.0.4 on 2020-05-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200511_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='url',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
