# Generated by Django 2.0.4 on 2020-05-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200511_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='client_photo',
            field=models.ImageField(blank=True, null=True, upload_to='client_profile/'),
        ),
    ]
