# Generated by Django 2.0.4 on 2020-05-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200511_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='client_photo',
            field=models.ImageField(default=1, upload_to='client_profile/'),
            preserve_default=False,
        ),
    ]
