# Generated by Django 2.0.4 on 2020-05-28 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200528_2247'),
        ('base', '0009_auto_20200511_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='client_ptr',
        ),
        migrations.RemoveField(
            model_name='private',
            name='client_ptr',
        ),
        migrations.AlterField(
            model_name='remark',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_remarks', to='accounts.Client'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Private',
        ),
    ]
