# Generated by Django 2.0.4 on 2020-05-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200528_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
