# Generated by Django 2.0.4 on 2020-06-07 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200607_0120'),
        ('base', '0011_auto_20200529_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], max_length=10)),
                ('approved', models.BooleanField(default=False)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Invested amount($)')),
                ('phone_number', models.CharField(max_length=16)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='accounts.Client')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='base.Investment')),
            ],
        ),
    ]
