# Generated by Django 2.0.4 on 2020-06-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_client_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_investment',
            name='payment_token',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
