# Generated by Django 2.0.4 on 2020-06-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_client_investment_payment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_investment',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
