# Generated by Django 2.0.4 on 2020-06-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_client_investment_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_investment',
            name='payment_token',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
