# Generated by Django 2.0.4 on 2020-06-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20200608_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_investment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
