# Generated by Django 2.0.4 on 2020-06-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_client_investment_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='current_state',
            field=models.CharField(choices=[('Repaired/built', 'Repaired/built'), ('Performing asset', 'Performing asset')], default='Performing asset', max_length=255),
        ),
    ]
